// Generated by nitro
import type { Serialize, Simplify } from "nitro/types";
declare module "nitro/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/[...]').default>>>>
    }
  }
}
export {}