packages:
  - src/*
  - infra/*
  - www/*
catalog:
  '@eslint/js': ^9.25.0
  '@types/node': ^22.14.1
  '@types/react': ^18.3.20
  '@types/react-dom': ^18.3.6
  '@types/serve-handler': ^6.1.4
  ansi-to-pre: ^1.0.6
  esbuild: ^0.25.2
  eslint: ^9.25.0
  graph-run: ^1.0.4
  lru-cache: ^11.1.0
  p-retry: ^6.2.1
  package-json-from-dist: ^1.0.1
  pacote: ^21.0.0
  path-scurry: ^2.0.0
  polite-json: ^5.0.0
  prettier: ^3.5.3
  promise-call-limit: ^3.0.2
  resolve-import: ^2.0.0
  rimraf: ^6.0.1
  semver: ^7.7.1
  serve-handler: ^6.1.6
  tap: ^21.1.0
  tar: ^7.4.3
  tshy: ^3.0.2
  typedoc: ~0.27.6
  typescript: 5.7.3
  typescript-eslint: ^8.30.1
  walk-up-path: ^4.0.0
