packages:
  - src/*
  - infra/*
  - www/*
catalog:
  '@eslint/js': ^9.20.0
  '@types/eslint__js': ^8.42.3
  '@types/node': ^22.13.1
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.1
  chalk: ^5.3.0
  esbuild: ^0.23.1
  eslint: ^9.20.0
  graph-run: ^1.0.4
  lru-cache: ^11.0.2
  package-json-from-dist: ^1.0.0
  pacote: ^18.0.6
  path-scurry: ^2.0.0
  polite-json: ^5.0.0
  prettier: ^3.4.2
  rimraf: ^6.0.1
  semver: ^7.7.1
  tap: ^21.0.2
  tar: ^7.4.3
  tshy: ^3.0.2
  typescript: 5.7.3
  typescript-eslint: ^8.23.0
  walk-up-path: ^4.0.0
