packages:
  - src/*
  - infra/*
  - www/*
catalog:
  '@eslint/js': ^9.8.0
  '@radix-ui/react-slot': ^1.1.0
  '@types/eslint__js': ^8.42.3
  '@types/node': ^22.4.1
  '@types/react': ^18.3.11
  '@types/react-dom': ^18.3.1
  chalk: ^5.3.0
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  esbuild: ^0.23.1
  eslint: ^9.8.0
  graph-run: ^1.0.4
  lru-cache: ^11.0.2
  lucide-react: ^0.453.0
  package-json-from-dist: ^1.0.0
  pacote: ^18.0.6
  path-scurry: ^2.0.0
  polite-json: ^5.0.0
  prettier: ^3.3.2
  react: ^18.3.1
  react-dom: ^18.3.1
  rimraf: ^6.0.1
  semver: ^7.6.3
  tailwind-merge: ^2.5.2
  tailwindcss: ^3.4.14
  tailwindcss-animate: ^1.0.7
  tap: ^21.0.1
  tar: ^7.4.3
  tshy: ^3.0.2
  typescript: ^5.5.4
  typescript-eslint: ^8.0.1
  vitest: ^2.1.3
  walk-up-path: ^4.0.0
