packages:
  - src/*
  - infra/*
  - www/*
catalog:
  '@eslint/js': ^9.8.0
  '@types/eslint__js': ^8.42.3
  '@types/node': ^22.4.1
  chalk: ^5.3.0
  eslint: ^9.8.0
  graph-run: ^1.0.4
  lru-cache: ^11.0.0
  package-json-from-dist: ^1.0.0
  pacote: ^18.0.6
  path-scurry: ^2.0.0
  polite-json: ^5.0.0
  prettier: ^3.3.2
  rimraf: ^6.0.1
  semver: ^7.6.3
  tap: ^21.0.1
  tar: ^7.4.3
  tshy: ^3.0.2
  typedoc: ^0.26.5
  typescript: ^5.5.4
  typescript-eslint: ^8.0.1
  walk-up-path: ^4.0.0
