dangerouslyAllowAllBuilds: true
packages:
  - src/*
  - infra/*
  - www/*
catalog:
  '@eslint/js': ^9.39.2
  '@types/node': ^22.19.3
  '@types/pacote': '^11.1.8'
  '@types/semver': '^7.7.1'
  '@types/ssri': '^7.1.5'
  eslint: ^9.39.2
  lru-cache: ^11.2.4
  lz-string: ^1.5.0
  minimatch: ^10.1.1
  p-retry: ^7.1.1
  package-json-from-dist: ^1.0.1
  pacote: ^21.0.4
  path-scurry: ^2.0.1
  polite-json: ^5.0.0
  postcss-selector-parser: ^7.1.1
  prettier: ^3.7.4
  promise-call-limit: ^3.0.2
  rimraf: ^6.1.2
  semver: ^7.7.3
  ssri: ^13.0.0
  tap: ^21.5.0
  tar: ^7.5.2
  typedoc: ~0.27.9
  typescript-eslint: ^8.52.0
  typescript: 5.7.3
  walk-up-path: ^4.0.0
