#!/bin/bash
set -eo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/../../" && pwd)"
NODE_OPTIONS="--no-warnings --enable-source-maps --experimental-strip-types" __VLT_INTERNAL_LIVE_RELOAD="1" $(which node) "$ROOT_DIR/infra/build/src/bins/vlt.ts" "$@"
