/* GENERATED by scripts/perry/gen/daemon-modules.mjs — do not edit.
 *
 * Detached-worker plumbing, shared by the parent and the child.
 *
 * The Node builds keep the code-split contract: the parent runs
 * `process.execPath <script>`, the child reads stdin to EOF. Neither
 * survives compilation — `import.meta.filename` is a build-machine path so
 * there is no second script to run, and compiled stdin delivers `data` only
 * while a live handle keeps the loop turning and never emits `end` at all.
 * So the compiled parent re-executes the binary itself with
 * `VLT_INTERNAL_CMD` naming the worker, and terminates the payload with an
 * EOT byte rather than relying on EOF.
 *
 * Regenerate: node scripts/perry/gen/daemon-modules.mjs
 */
import { accessSync, constants, realpathSync } from 'node:fs'
import { resolve } from 'node:path'
import type EventEmitter from 'node:events'

/** end-of-payload sentinel; the compiled runtime never signals EOF on stdin */
export const EOT = '\x04'

/** the VLT_INTERNAL_CMD this package's worker answers to */
export const daemonCommand = 'cache-unzip'

const compiled = 'perry' in process.versions

const isDeno =
  (globalThis as typeof globalThis & { Deno?: any }).Deno != undefined

/** Deno on Windows has no detached processes (denoland/deno#25867) */
export const detached = !(isDeno && process.platform === 'win32')

/** absolute, launch-mode-independent path to this executable */
const selfExe = (): string => {
  try {
    return realpathSync('/proc/self/exe')
  } catch {
    /* no procfs — macOS and Windows fall through */
  }
  // compiled, process.execPath is argv[0] verbatim, so under a bare-name
  // PATH launch it is not a path at all: resolve it as the shell did.
  const p = process.execPath
  if (p.includes('/') || p.includes('\\'))
    return realpathSync(resolve(p))
  for (const dir of (process.env.PATH ?? '').split(
    process.platform === 'win32' ? ';' : ':',
  )) {
    try {
      const c = resolve(dir, p)
      accessSync(c, constants.X_OK)
      return realpathSync(c)
    } catch {}
  }
  return p
}

/**
 * How to launch this package's detached worker. `script` is the code-split
 * entry, which only the Node builds use.
 */
export const daemonSpawn = (
  script: string,
): { command: string; args: string[]; env: NodeJS.ProcessEnv } => {
  if (compiled)
    return {
      command: selfExe(),
      args: [],
      env: { VLT_INTERNAL_CMD: daemonCommand },
    }
  const args: string[] = []
  // running deno from source needs the unstable flags; -A is automatic
  if (isDeno)
    args.push(
      '--unstable-node-globals',
      '--unstable-bare-node-builtins',
    )
  args.push(script)
  return { command: process.execPath, args, env: {} }
}

/** terminate the payload: the sentinel, then EOF for the Node builds */
export const endPayload = (stdin: NodeJS.WritableStream): void => {
  stdin.write(EOT)
  stdin.end()
}

/** the whole stdin payload, up to the sentinel or (under Node) EOF */
export const readPayload = (
  stdinOverride?: EventEmitter,
): Promise<string> =>
  new Promise((res, rej) => {
    // `?? process.stdin` here, NEVER `= process.stdin` in the parameter:
    // compiled, stdin routed through a parameter slot (default or
    // explicit argument) loses its event delivery and 'data' never
    // fires. A fallback bound inside the body works. (notes F48)
    const input = stdinOverride ?? process.stdin
    // the live handle is what makes 'data' fire at all when compiled
    const keepAlive = setInterval(() => {}, 50)
    const chunks: Buffer[] = []
    let len = 0
    const done = () => {
      clearInterval(keepAlive)
      res(Buffer.concat(chunks, len).toString())
    }
    input.on('data', (chunk: Buffer | string) => {
      const b = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)
      const i = b.indexOf(0x04)
      const keep = i === -1 ? b : b.subarray(0, i)
      chunks.push(keep)
      len += keep.length
      if (i !== -1) done()
    })
    input.on('end', done)
    input.on('error', (er: Error) => {
      clearInterval(keepAlive)
      rej(er)
    })
  })
