/* GENERATED by scripts/perry/gen/commands-map.mjs — do not edit.
 *
 * Static command dispatch. `import()` below module top level is silently
 * dropped by the compiler (perry-notes F4) and a template-literal specifier
 * fails `check --check-deps` (S2), so the compiled binary cannot load
 * commands lazily. Every command's dep closure therefore links into the
 * binary whether or not it runs.
 *
 * Regenerate after adding a command: node scripts/perry/gen/commands-map.mjs
 */
import * as access from './commands/access.ts'
import * as bugs from './commands/bugs.ts'
import * as build from './commands/build.ts'
import * as cache from './commands/cache.ts'
import * as ci from './commands/ci.ts'
import * as config from './commands/config.ts'
import * as create from './commands/create.ts'
import * as deprecate from './commands/deprecate.ts'
import * as distTag from './commands/dist-tag.ts'
import * as docs from './commands/docs.ts'
import * as exec from './commands/exec.ts'
import * as execCache from './commands/exec-cache.ts'
import * as execLocal from './commands/exec-local.ts'
import * as help from './commands/help.ts'
import * as init from './commands/init.ts'
import * as install from './commands/install.ts'
import * as list from './commands/list.ts'
import * as login from './commands/login.ts'
import * as logout from './commands/logout.ts'
import * as pack from './commands/pack.ts'
import * as ping from './commands/ping.ts'
import * as pkg from './commands/pkg.ts'
import * as profile from './commands/profile.ts'
import * as publish from './commands/publish.ts'
import * as query from './commands/query.ts'
import * as registry from './commands/registry.ts'
import * as repo from './commands/repo.ts'
import * as run from './commands/run.ts'
import * as runExec from './commands/run-exec.ts'
import * as setup from './commands/setup.ts'
import * as token from './commands/token.ts'
import * as uninstall from './commands/uninstall.ts'
import * as unpublish from './commands/unpublish.ts'
import * as update from './commands/update.ts'
import * as version from './commands/version.ts'
import * as view from './commands/view.ts'
import * as whoami from './commands/whoami.ts'

import type { Command } from './load-command.ts'
import type { Commands } from './config/definition.ts'

export const commandModules = {
  access: access,
  bugs: bugs,
  build: build,
  cache: cache,
  ci: ci,
  config: config,
  create: create,
  deprecate: deprecate,
  'dist-tag': distTag,
  docs: docs,
  exec: exec,
  'exec-cache': execCache,
  'exec-local': execLocal,
  help: help,
  init: init,
  install: install,
  list: list,
  login: login,
  logout: logout,
  pack: pack,
  ping: ping,
  pkg: pkg,
  profile: profile,
  publish: publish,
  query: query,
  registry: registry,
  repo: repo,
  run: run,
  'run-exec': runExec,
  setup: setup,
  token: token,
  uninstall: uninstall,
  unpublish: unpublish,
  update: update,
  version: version,
  view: view,
  whoami: whoami,
} as unknown as Record<Commands[keyof Commands], Command<unknown>>
