/* GENERATED by scripts/perry/gen/prompt-modules.mjs — do not edit.
 *
 * One-line prompts, without `node:readline/promises`.
 *
 * `createInterface` is non-functional in the compiled binary, and the stdin
 * underneath it only delivers `data` while a live handle keeps the loop
 * turning — and never signals EOF at all. So the prompt is written straight to
 * the output stream and the answer is read off the first newline.
 *
 * The terminal is left in canonical mode, so echo, backspace and line editing
 * are still the tty driver's job, as they were under readline.
 *
 * Regenerate: node scripts/perry/gen/prompt-modules.mjs
 */
import type { Readable } from 'node:stream'

export type PromptStreams = {
  input?: NodeJS.ReadableStream
  output?: NodeJS.WritableStream
}

/**
 * Everything read past the newline of the last answer. A piped stdin hands
 * over every line in one chunk, so a prompt that stopped at its own newline
 * and dropped the rest would leave the next prompt waiting forever.
 */
const leftover = new Map<NodeJS.ReadableStream, string>()

/** the next line of `input`, without its terminator; '' at end of input */
export const readLine = (
  input: NodeJS.ReadableStream = process.stdin,
): Promise<string> => {
  const held = leftover.get(input) ?? ''
  const nl = held.indexOf('\n')
  if (nl !== -1) {
    leftover.set(input, held.slice(nl + 1))
    return Promise.resolve(held.slice(0, nl).replace(/\r$/, ''))
  }
  return new Promise((res, rej) => {
    const stream = input as Readable
    // the live handle is what makes 'data' fire at all when compiled
    const keepAlive = setInterval(() => {}, 50)
    let buf = held
    const done = (line: string, rest: string) => {
      clearInterval(keepAlive)
      stream.off('data', onData)
      stream.pause()
      leftover.set(input, rest)
      res(line)
    }
    const onData = (chunk: Buffer | string) => {
      buf += String(chunk)
      const i = buf.indexOf('\n')
      if (i !== -1)
        done(buf.slice(0, i).replace(/\r$/, ''), buf.slice(i + 1))
    }
    stream.on('data', onData)
    stream.once('end', () => done(buf, ''))
    stream.once('error', (er: Error) => {
      clearInterval(keepAlive)
      rej(er)
    })
    stream.resume()
  })
}

/** write `text`, then read one line of input */
export const question = async (
  text: string,
  {
    input = process.stdin,
    output = process.stdout,
  }: PromptStreams = {},
): Promise<string> => {
  output.write(text)
  return await readLine(input)
}
