/* GENERATED by scripts/perry/gen/version-modules.mjs — do not edit.
 *
 * The runtime version lookup does not survive compilation:
 * `import.meta.filename` keeps the build machine's source path,
 * no package.json ships beside the binary, and there is
 * no esbuild `define` in that build. So the compiled build reads the
 * literal below and the Node builds keep the lookup, which stays
 * authoritative for a published package.
 *
 * Regenerate after a version bump: node scripts/perry/gen/version-modules.mjs
 */
import { loadPackageJson } from 'package-json-from-dist'

const compiled = '1.0.7'

export const version: string =
  'perry' in process.versions ?
    compiled
  : (
      loadPackageJson(
        import.meta.filename,
        process.env.__VLT_INTERNAL_CLI_PACKAGE_JSON,
      ) as { version: string }
    ).version
