#!/bin/sh

SCRIPT_DIR="$(cd "$(dirname "$0")/../../../" && pwd)"
if [ ! -d "$SCRIPT_DIR/.build-bundle" ]; then
  echo "Run 'pnpm run build:bundle' first."
  exit 1
fi
deno -A --unstable-bare-node-builtins --unstable-node-globals $SCRIPT_DIR/.build-bundle/vlrx.js "$@"
