#!/bin/bash
set -eo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/../../../" && pwd)"
if [ ! -f "$ROOT_DIR/.build-bundle/vlx.js" ]; then
  (cd $ROOT_DIR && pnpm vlt-build --bins=vlx --outdir=".build-bundle" bundle > /dev/null 2>&1)
fi
deno -A "$ROOT_DIR/.build-bundle/vlx.js" "$@"
